# Generated by Django 4.2.6 on 2023-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='title',
            field=models.CharField(default=4325124, max_length=50),
            preserve_default=False,
        ),
    ]
